# Generated by Django 3.0.3 on 2020-02-09 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fe7', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
