# Generated by Django 3.0.3 on 2020-02-09 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fe7', '0002_basestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestats',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basestats',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_stats', to='fe7.Character'),
        ),
    ]
