# Generated by Django 3.0.3 on 2020-02-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe7', '0004_auto_20200209_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='base_class',
            field=models.CharField(choices=[('Lord (Lyndis)', 'Lord (Lyndis)'), ('Blade Lord', 'Blade Lord'), ('Lord (Eliwood)', 'Lord (Eliwood)'), ('Knight Lord', 'Knight Lord'), ('Lord (Hector)', 'Lord (Hector)'), ('Great Lord', 'Great Lord'), ('Mercenary', 'Mercenary'), ('Hero', 'Hero'), ('Myrmidon', 'Myrmidon'), ('Swordmaster', 'Swordmaster'), ('Thief', 'Thief'), ('Assassin', 'Assassin'), ('Armour Knight', 'Armour Knight'), ('General', 'General'), ('Fighter', 'Fighter'), ('Warrior', 'Warrior'), ('Bandit', 'Bandit'), ('Pirate', 'Pirate'), ('Beserker', 'Beserker'), ('Archer', 'Archer'), ('Sniper', 'Sniper'), ('Nomad', 'Nomad'), ('Nomad Trooper', 'Nomad Trooper'), ('Cavalier', 'Cavalier'), ('Paladin', 'Paladin'), ('Pegasus Knight', 'Pegasus Knight'), ('Falcon Knight', 'Falcon Knight'), ('Wyvern Rider', 'Wyvern Rider'), ('Wyvern Lord', 'Wyvern Lord'), ('Monk', 'Monk'), ('Cleric', 'Cleric'), ('Bishop', 'Bishop'), ('Troubadour', 'Troubadour'), ('Valkyrie', 'Valkyrie'), ('Mage', 'Mage'), ('Sage', 'Sage'), ('Archsage', 'Archsage'), ('Shaman', 'Shaman'), ('Druid', 'Druid'), ('Dark Druid', 'Dark Druid'), ('Bard', 'Bard'), ('Dancer', 'Dancer')], default='Cavalier', max_length=20),
        ),
    ]
