# Generated by Django 3.0.3 on 2020-02-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe7', '0006_character_recruitment_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='magic_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='strength_user',
            field=models.BooleanField(default=True),
        ),
    ]
