# Generated by Django 3.0.3 on 2020-02-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fe7', '0008_auto_20200209_0110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='BaseStats',
        ),
    ]
