# Generated by Django 3.0.3 on 2020-02-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fe7', '0009_auto_20200209_0125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseStats',
            new_name='Stats',
        ),
    ]
