# Generated by Django 3.0.3 on 2020-02-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fe7', '0010_auto_20200209_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='BaseStats',
        ),
    ]
