# Generated by Django 3.0.3 on 2020-02-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe7', '0012_growthrates'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthrates',
            name='defence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='growthrates',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='growthrates',
            name='luck',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='growthrates',
            name='magic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='growthrates',
            name='resistance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='growthrates',
            name='skill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='growthrates',
            name='speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='growthrates',
            name='strength',
            field=models.IntegerField(default=0),
        ),
    ]
