# Generated by Django 3.0.3 on 2020-02-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe7', '0013_auto_20200209_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestats',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
