# Generated by Django 3.0.3 on 2020-02-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fe7', '0014_basestats_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='affinity',
            field=models.CharField(choices=[('FI', 'Fire'), ('TH', 'Thunder'), ('WD', 'Wind'), ('IC', 'Ice'), ('DK', 'Dark'), ('LT', 'Light'), ('AN', 'Anima')], default='FI', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
